### ISSUE TITLE
client.guilds.get is not a function

### ISSUE THREAD

**Issue by alekitopi** [Sank6/Backup#4]
When I enter into the website, the bot shows this error:
```
TypeError: client.guilds.get is not a function
    at /root/Backup/server.js:133:21
    at Layer.handle [as handle_request] (/root/Backup/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/Backup/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/Backup/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/Backup/node_modules/express/lib/router/layer.js:95:5)
    at /root/Backup/node_modules/express/lib/router/index.js:281:22
    at param (/root/Backup/node_modules/express/lib/router/index.js:354:14)
    at param (/root/Backup/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/root/Backup/node_modules/express/lib/router/index.js:410:3)
    at next (/root/Backup/node_modules/express/lib/router/index.js:275:10)
```

**Comment by Sank6** [comment]
That would be Discord.js v12.  You need to add `.cache`
