### ISSUE TITLE
domain is not defined

### ISSUE THREAD

**Issue by alekitopi** [Sank6/Backup#5]
When I select a server in the website, it shows an error related with a variable.
```
[2020-03-18 22:27:23] Uncaught Promise Error: 
[2020-03-18 22:27:23] ReferenceError: domain is not defined
[2020-03-18 22:27:23]     at Timeout._onTimeout (/root/Backup/server.js:227:10)
[2020-03-18 22:27:23]     at listOnTimeout (internal/timers.js:549:17)
[2020-03-18 22:27:23]     at processTimers (internal/timers.js:492:7)
```

**Comment by Sank6** [comment]
Fixed: cb1544c
